"""Rebuild the headline tables of notes.md from the results registry (writes results/tables.md).

Means over seeds; the seed values are listed where a claim rests on them. Superseded and smoke runs are left out.

    uv run build_registry.py && uv run make_tables.py
"""
import math
import os
from collections import defaultdict

import registry

OUT = os.path.join(registry.ROOT, "results", "tables.md")


def rows(**where):
    out = []
    for r in registry.load():
        if r.get("superseded") or r.get("smoke"):
            continue
        if all((r.get(k) in v) if isinstance(v, (set, tuple, list)) else r.get(k) == v for k, v in where.items()):
            out.append(r)
    return out


def group(rs, key):
    g = defaultdict(list)
    for r in rs:
        g[key(r)].append(r)
    return g


def mean(rs, f):
    v = [r[f] for r in rs if f in r and not (isinstance(r[f], float) and math.isnan(r[f]))]
    return sum(v) / len(v) if v else float("nan")


def pct(x):
    return "" if math.isnan(x) else f"{100 * x:.1f}%"


def seeds(rs, f):
    return ", ".join(f"{100 * r[f]:.1f}" for r in sorted(rs, key=lambda r: r.get("seed", 0)) if f in r)


def table(title, note, header, body):
    s = f"## {title}\n\n" + (f"{note}\n\n" if note else "") + "| " + " | ".join(header) + " |\n|" + "---|" * len(header) + "\n"
    return s + "".join("| " + " | ".join(str(c) for c in row) + " |\n" for row in body) + "\n"


def mlx_rules(experiment, order=None, **where):
    """Per rule: patch rate, computed / final / boxed accuracy, bpb, seeds."""
    g = group(rows(experiment=experiment, **where), lambda r: r["rule"])
    names = [n for n in (order or sorted(g)) if n in g]
    return [[n, f"{mean(g[n], 'rate'):.3f}", pct(mean(g[n], "computed_acc")), pct(mean(g[n], "final_acc")),
             pct(mean(g[n], "boxed_acc")), f"{mean(g[n], 'bpb'):.3f}", len(g[n]),
             seeds(g[n], "computed_acc")] for n in names]


HDR = ["rule", "patch rate", "computed", "final", "boxed (MATH)", "bpb", "seeds", "computed by seed"]


def main():
    out = ["# Tables rebuilt from the results registry\n\nGenerated by `make_tables.py` from `results/registry/*.jsonl`. "
           "Accuracy is greedy exact match of each target given the true prefix (teacher-forced context).\n"]
    out.append(table("Specialized math, small model (D=64, 2 global layers)", "GSM8K + MATH, 32k steps, cross-attention pooling, windowed local decoder.",
                     HDR, mlx_rules("math_small", ["entropy", "jump", "syntax+jump", "words", "words+jump", "words+syntax"])))
    out.append(table("New math strategies (D=64), up to 5 seeds", "Per-digit and operand-aligned patches against matched random controls.",
                     HDR, mlx_rules("math_new_strategies")))
    out.append(table("Larger model (D=128, 4 global layers)", "Attribution: word alignment and the result boundary.",
                     HDR, mlx_rules("math_larger", ["entropy", "jump", "words", "stride6+syntax", "words+syntax"])))
    for exp, title in (("scratchpad8", "Scratchpad Patching, 8-byte patches (sum pooling)"),
                       ("scratchpad16", "Scratchpad Patching, 16-byte patches (cross-attention pooling)")):
        out.append(table(title, "Fixed patches plus 6% scratchpads chosen by the trigger after the colon.", HDR, mlx_rules(exp)))

    # tight budgets: budget x rule
    g = group(rows(experiment="math_tight_budget"), lambda r: r["rule"])
    body = []
    for R in (10, 15, 20):
        row = [f"{R}%"]
        for kind in ("entropy", "dep", "syntax+entropy"):
            rs = g.get(f"{kind}{R}", [])
            row.append(f"{pct(mean(rs, 'computed_acc'))} / {pct(mean(rs, 'final_acc'))} / {mean(rs, 'bpb'):.3f} (n={len(rs)})" if rs else "")
        body.append(row)
    out.append(table("Training at tight budgets (D=128, 4 global layers): computed / final / bpb",
                     "dep = label-free boundary dependence (deptrigger.py, marginal mode); syntax+entropy = hand-written result boundaries.",
                     ["budget", "BLT entropy", "dependence (no labels)", "hand-written"], body))
    out.append(table("Tight budgets, all rules", "", HDR, mlx_rules("math_tight_budget")))

    for w in (32, 8):
        g = group(rows(experiment="reason_trained", window=w), lambda r: r["rule"])
        body = [[n, len(g[n]), pct(mean(g[n], "computed_acc")), f"{mean(g[n], 'computed_bits'):.2f}", pct(mean(g[n], "copy_acc")),
                 pct(mean(g[n], "final_acc")), pct(mean(g[n], "boxed_acc")), seeds(g[n], "computed_acc")]
                for n in ("entropy", "entropy10", "jump10", "syntax+entropy10", "entdep10") if n in g]
        out.append(table(f"Logic and program traces trained here, local window {w} bytes",
                         "computed / copied trace values, logic answer (Yes/No), proof-step conclusion.",
                         ["rule", "seeds", "computed", "computed bits", "copied", "logic answer", "proof step", "computed by seed"], body))

    g = group(rows(script="realtext"), lambda r: (r.get("experiment"), r["data"], r["rule"]))
    body = [[e, d, n, len(rs), f"{mean(rs, 'computed_bits'):.3f}", f"{mean(rs, 'final_bits'):.3f}", f"{mean(rs, 'text_bits'):.3f}",
             f"{mean(rs, 'rate'):.3f}"] for (e, d, n), rs in sorted(g.items())]
    out.append(table("Real text (GSM8K, code), bits per byte", "realtext_wordstart_fix = reruns after the causal word-start fix.",
                     ["experiment", "data", "rule", "seeds", "computed bits", "final bits", "text bits", "rate"], body))

    # BLT-1B: train-fitted thresholds (#26 reruns) and the original per-problem selection. The #26 problem-mode
    # reruns reproduce the originals exactly, so they are not repeated here.
    def blt(exp, thresh):
        return [r for r in rows(experiment=exp, thresh=thresh) if bool(r.get("rerun")) == (thresh == "train")]
    for thresh in ("train", "problem"):
        body = [[r["layout"], f"{r.get('rate', float('nan')):.3f}", pct(r.get("results_covered", float("nan"))),
                 pct(r.get("results_exact", float("nan"))), pct(r.get("final_exact", float("nan")))] for r in blt("blt_budget", thresh)]
        out.append(table(f"BLT-1B tight-budget layouts on GSM8K ({thresh} thresholds)",
                         "294 test problems, 796 in-line results; patch boundaries changed at inference.",
                         ["layout", "patch rate", "results covered", "in-line results exact", "final exact"], body))
    for exp, cols in (("blt_code", [("ident_exact", "repeated identifiers")]),
                      ("blt_trace", [("computed_exact", "computed"), ("copy_exact", "copied")]),
                      ("blt_logic", [("step_exact", "proof step"), ("answer_choice", "answer (forced choice)")]),
                      ("blt_direct", [("answer_choice", "answer (forced choice)")])):
        for thresh in ("train", "problem"):
            sub = blt(exp, thresh)
            if sub:
                out.append(table(f"BLT-1B {exp[4:]} ({thresh} thresholds)", "exact match unless noted",
                                 ["layout"] + [lab for _, lab in cols],
                                 [[r["layout"]] + [pct(r.get(k, float("nan"))) for k, _ in cols] for r in sub]))
    sub = rows(experiment="blt_answer_boundary")
    out.append(table("BLT-1B: patch start at the final answer", "300 GSM8K problems, final answer given the worked solution.",
                     ["layout", "bits per answer byte", "exact"], [[r["layout"], f"{r['answer_bits']:.3f}", pct(r["answer_exact"])] for r in sub]))
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print("wrote", os.path.relpath(OUT, registry.ROOT), f"({sum(s.count(chr(10) + '| ') for s in out)} rows)")


if __name__ == "__main__":
    main()
